insert into menu_categories (slug, name, display_order)
values
    ('bites-to-start', 'BITES TO START', 1),
    ('sourdough-pizza-calzone', 'SOURDOUGH PIZZA & CALZONE', 2),
    ('specials', 'SPECIALS', 3),
    ('sweet-tooth', 'SWEET TOOTH', 4),
    ('side-salad', 'SIDE SALAD', 5);

insert into menu_items (
    category_id,
    slug,
    name,
    description,
    price_pence,
    image_path,
    product_type,
    available,
    active,
    featured,
    customizable,
    display_order
)
values
    ((select id from menu_categories where slug = 'bites-to-start'), 'olive-di-nocellara', 'OLIVE DI NOCELLARA', 'Mixed olives from Nocellara of Belice.', 345, null, 'STANDARD', true, true, false, false, 1),
    ((select id from menu_categories where slug = 'bites-to-start'), 'schiacciatella', 'SCHIACCIATELLA', 'Pizza bread with garlic oil & rosemary sprinkled with sea salt.', 445, '/images/menu/schiacciatella.png', 'STANDARD', true, true, true, false, 2),
    ((select id from menu_categories where slug = 'bites-to-start'), 'bruschetta', 'BRUSCHETTA', 'Ide of wychy tomatoes, red onions and roasted garlic marinated in a special and delicious dressing, served on toasted sourdough, with a light and fresh base of parmesan.', 545, null, 'STANDARD', true, true, false, false, 3),
    ((select id from menu_categories where slug = 'bites-to-start'), 'schiacciata-al-formaggio', 'SCHIACCIATA AL FORMAGGIO', 'Pizza bread with cheese, garlic oil & rosemary sprinkled with sea salt.', 565, null, 'STANDARD', true, true, false, false, 4),
    ((select id from menu_categories where slug = 'bites-to-start'), 'oppane-the-bread', 'OPPĀNE (THE BREAD)', 'Made from sourdough, toscano, bread stick and mini pizzette served with olive oil and basil.', 595, null, 'STANDARD', true, true, false, false, 5),
    ((select id from menu_categories where slug = 'bites-to-start'), 'piadina-e-crema-di-pomodoro', 'PIADINA E CREMA DI POMODORO', 'Slow-roasted Isle of Wight tomato hummus, roasted seeds and olives, served with homemade flat bread.', 645, null, 'STANDARD', true, true, false, false, 6),
    ((select id from menu_categories where slug = 'bites-to-start'), 'sfizio-al-pomodoro', 'SFIZIO AL POMODORO', 'Buffalo mozzarella from campana isle of wychy tomato, beef tomato with Trapani salt, Grana Padano, rocket, onions and extra basil.', 695, null, 'STANDARD', true, true, false, false, 7),
    ((select id from menu_categories where slug = 'bites-to-start'), 'tagliere-misto-sharing-platter-for-2', 'TAGLIERE MISTO (A SHARING PLATTER FOR 2)', 'Buffalo mozzarella from campana isle of wychy tomato, beef tomato with trapani salt, grana padano, rocket, onions and extra basil.', 1295, null, 'STANDARD', true, true, false, false, 8),
    ((select id from menu_categories where slug = 'sourdough-pizza-calzone'), 'pizza-margherita', 'PIZZA MARGHERITA', 'Crushed San Marzano tomatoes, fior di latte cheese, parmesan DOP, extra virgin olive oil and fresh basil. [Choose Buffalo mozzarella instead on any pizza for £2.75]', 899, '/images/menu/margherita.png', 'PIZZA', true, true, true, false, 1),
    ((select id from menu_categories where slug = 'sourdough-pizza-calzone'), 'lerrore-the-mistake', 'L''ERRORE (THE MISTAKE)', 'Crushed San Marzano tomatoes, fior di latte cheese, fresh caramelised pineapple pieces and honey roasted ham.', 999, null, 'PIZZA', true, true, false, false, 2),
    ((select id from menu_categories where slug = 'sourdough-pizza-calzone'), 'piccante-formaggiata', 'PICCANTE FORMAGGIATA', 'For those who love a bit of a kick, our Piccante Formaggiata pizza is a must-try. This pizza features a zesty tomato base loaded with crunchy onions, bell peppers, fresh tomatoes, and spicy jalapeños, all generously topped with double cheese for a mouthwatering finish.', 1199, null, 'PIZZA', true, true, false, false, 3),
    ((select id from menu_categories where slug = 'sourdough-pizza-calzone'), 'tofu-mediterraneo', 'TOFU MEDITERRANEO', 'Discover a delightful fusion of Mediterranean flavours with our Tofu Mediterraneo pizza. A rich tomato base is generously topped with marinated tofu cubes, sun-dried tomatoes, roasted red peppers, artichoke hearts, and a sprinkle of fresh oregano. This plant-based pizza offers a perfect balance of savoury and tangy notes, making it a delicious and healthy choice for all pizza lovers.', 1299, null, 'PIZZA', true, true, false, false, 4),
    ((select id from menu_categories where slug = 'sourdough-pizza-calzone'), 'a-bella-figliola', 'A BELLA FIGLIOLA', 'Fior di latte cheese, blanched asparagus tips, creamy goat cheese, red onion marmalade, mild chilli & lemon compote dressed with extra virgin oil.', 1199, null, 'PIZZA', true, true, false, false, 5),
    ((select id from menu_categories where slug = 'sourdough-pizza-calzone'), 'pizza-e-fantasia', 'PIZZA E FANTASIA', 'White base of ricotta and fior di latte cheese, courgettes, Isle of Wight tomatoes and capers finished with caramelised lemon zest. [Vegan cheese instead of mozzarella or as an extra topping £1.95]', 1199, null, 'PIZZA', true, true, false, false, 6),
    ((select id from menu_categories where slug = 'sourdough-pizza-calzone'), 'pizza-cacio-e-pepe', 'PIZZA CACIO E PEPE', 'White base pizza topped with fior di latte cheese, goat cheese, ricotta cheese and gorgonzola finished with freshly ground black pepper. [Add tomato sauce or rainbow cherry tomatoes for £1.95]', 1099, null, 'PIZZA', true, true, false, false, 7),
    ((select id from menu_categories where slug = 'sourdough-pizza-calzone'), 'alicella-sagliuta', 'ALICELLA SAGLIUTA', 'San Marzano tomato sauce, fior di latte cheese, Isle of Wight cherry tomatoes, Pantelleria capers, Nocellara olives, Cetara anchovies, garlic oil and fresh basil. [Add chilli & lemon compote for £1.95]', 1299, null, 'PIZZA', true, true, false, false, 8),
    ((select id from menu_categories where slug = 'sourdough-pizza-calzone'), 'verdure-fresche', 'VERDURE FRESCHE', 'Experience the freshness of our Verdure Fresche pizza, adorned with a vibrant mix of bell peppers, mushrooms, raw onions, juicy fresh tomatoes, and sweetcorn. Perfect for vegetable lovers, this pizza is a celebration of crisp, garden-fresh flavours on a classic tomato base.', 1099, null, 'PIZZA', true, true, false, false, 9),
    ((select id from menu_categories where slug = 'sourdough-pizza-calzone'), 'pepperoni-doppio-formaggio', 'PEPPERONI DOPPIO FORMAGGIO', 'Savour the ultimate cheesy delight with our Pepperoni Doppio Formaggio pizza. A robust tomato base is layered with spicy pepperoni and smothered in double cheese, delivering a rich and satisfying flavour in every slice. Perfect for cheese and meat lovers alike.', 1295, null, 'PIZZA', true, true, false, false, 10),
    ((select id from menu_categories where slug = 'sourdough-pizza-calzone'), 'o-core-e-napule', 'O CORE E NAPULE', 'Isle of Wight roasted tomato sauce, smoked garlic and Buffalo mozzarella, mushrooms, Nocellara olives, artichokes and roasted ham, finished Extra virgin oil & fresh parmesan', 1295, null, 'PIZZA', true, true, false, false, 11),
    ((select id from menu_categories where slug = 'sourdough-pizza-calzone'), 'pizza-do-putecaro', 'PIZZA DO PUTECARO', 'Lightly smoked beechwood spicy salami, Isle of Wight roasted tomato salsa, fior di latte cheese, red onion marmalade and crumble of gorgonzola dressed with ''nduja, mild chilli & lemon compote.', 1295, null, 'PIZZA', true, true, false, false, 12),
    ((select id from menu_categories where slug = 'sourdough-pizza-calzone'), 'pizza-bufala', 'PIZZA BUFALA', 'White base with Buffalo mozzarella, Parma ham, rainbow cherry tomatoes, shaved Parmesan cheese, basil & extra virgin olive oil. [Add rocket salad as an extra topping £1.95]', 1195, null, 'PIZZA', true, true, false, false, 13),
    ((select id from menu_categories where slug = 'sourdough-pizza-calzone'), 'lazzarella', 'LAZZARELLA', 'Beef Meat Ragout, fior di latte cheese, Buffalo meatballs, Buffalo Ricotta Cheese, basil and extra virgin olive oil.', 1295, null, 'PIZZA', true, true, false, false, 14),
    ((select id from menu_categories where slug = 'sourdough-pizza-calzone'), 'pollo-funghi-dolce', 'POLLO FUNGHI DOLCE', 'Indulge in our Pollo Funghi Dolce pizza, featuring a savoury tomato base topped with tender chicken, earthy mushrooms, and sweetcorn. A delightful combination that brings together rich flavours and a touch of sweetness in every bite.', 1295, null, 'PIZZA', true, true, false, false, 15),
    ((select id from menu_categories where slug = 'specials'), 'lasagna', 'LASAGNA', 'Layers of baked pasta with creamy Bolognese sauce, egg, mozzarella cheese and Parmesan DOP.', 1099, '/images/menu/lasagna.png', 'STANDARD', true, true, true, false, 1),
    ((select id from menu_categories where slug = 'specials'), 'parmigiana-di-melanzane', 'PARMIGIANA DI MELANZANE', 'Layered roasted aubergine bake, smoked provola mozzarella, Parmesan cheese and Italian tomato sauce.', 995, null, 'STANDARD', true, true, false, false, 2),
    ((select id from menu_categories where slug = 'specials'), 'the-italian-job', 'THE ITALIAN JOB', 'We believe in quality, so we have created a special blend of 100% Dorset reared minced beef for a perfect juicy 6oz burger, topped with blue cheese, bacon, caramelised red onions & gherkins finished with fresh salad & tomatoes in our homemade bread & accompanied with potato gratin.', 1295, null, 'STANDARD', true, true, false, false, 3),
    ((select id from menu_categories where slug = 'specials'), 'pollo-al-forno', 'POLLO AL FORNO', 'Chicken breast or thighs, roasted Isle of Wight cherry tomatoes, olives and buffalo mozzarella. Served with potato gratin.', 1195, null, 'STANDARD', true, true, false, false, 4),
    ((select id from menu_categories where slug = 'sweet-tooth'), 'tiramisu', 'TIRAMISÙ', 'Espresso & liqueur-soaked finger biscuit & layers of mascarpone & cocoa.', 599, null, 'STANDARD', true, true, false, false, 1),
    ((select id from menu_categories where slug = 'sweet-tooth'), 'triple-chocolate-brownie', 'TRIPLE CHOCOLATE BROWNIE', 'A deliciously decadent Triple Chocolate Brownie recipe that was inspired by dietary requirements and brought to life for you.', 599, null, 'STANDARD', true, true, false, false, 2),
    ((select id from menu_categories where slug = 'sweet-tooth'), 'calzone-alla-nutella', 'CALZONE ALLA NUTELLA', 'Sweet, warm dough filled with Nutella, banana & fluffy marshmallow drizzled with salted caramel sauce.', 599, '/images/menu/calzoneallanutella.png', 'STANDARD', true, true, true, false, 3),
    ((select id from menu_categories where slug = 'side-salad'), 'mixed-sides', 'MIXED SIDES', null, 450, null, 'STANDARD', true, true, false, false, 1),
    ((select id from menu_categories where slug = 'side-salad'), 'rocket-side', 'ROCKET SIDE', null, 495, null, 'STANDARD', true, true, false, false, 2);

insert into menu_item_dietary_tags (menu_item_id, tag)
values
    ((select id from menu_items where slug = 'olive-di-nocellara'), 'V'),
    ((select id from menu_items where slug = 'olive-di-nocellara'), 'GF'),
    ((select id from menu_items where slug = 'olive-di-nocellara'), 'VE'),
    ((select id from menu_items where slug = 'schiacciatella'), 'V'),
    ((select id from menu_items where slug = 'schiacciatella'), 'VE'),
    ((select id from menu_items where slug = 'bruschetta'), 'V'),
    ((select id from menu_items where slug = 'bruschetta'), 'VE'),
    ((select id from menu_items where slug = 'schiacciata-al-formaggio'), 'V'),
    ((select id from menu_items where slug = 'schiacciata-al-formaggio'), 'VE'),
    ((select id from menu_items where slug = 'oppane-the-bread'), 'V'),
    ((select id from menu_items where slug = 'oppane-the-bread'), 'VE'),
    ((select id from menu_items where slug = 'piadina-e-crema-di-pomodoro'), 'V'),
    ((select id from menu_items where slug = 'piadina-e-crema-di-pomodoro'), 'VE'),
    ((select id from menu_items where slug = 'sfizio-al-pomodoro'), 'V'),
    ((select id from menu_items where slug = 'sfizio-al-pomodoro'), 'GF'),
    ((select id from menu_items where slug = 'sfizio-al-pomodoro'), 'VE'),
    ((select id from menu_items where slug = 'tagliere-misto-sharing-platter-for-2'), 'VE'),
    ((select id from menu_items where slug = 'pizza-margherita'), 'V'),
    ((select id from menu_items where slug = 'pizza-margherita'), 'GF'),
    ((select id from menu_items where slug = 'pizza-margherita'), 'VE'),
    ((select id from menu_items where slug = 'lerrore-the-mistake'), 'V'),
    ((select id from menu_items where slug = 'lerrore-the-mistake'), 'GF'),
    ((select id from menu_items where slug = 'lerrore-the-mistake'), 'VE'),
    ((select id from menu_items where slug = 'piccante-formaggiata'), 'V'),
    ((select id from menu_items where slug = 'piccante-formaggiata'), 'GF'),
    ((select id from menu_items where slug = 'piccante-formaggiata'), 'VE'),
    ((select id from menu_items where slug = 'tofu-mediterraneo'), 'V'),
    ((select id from menu_items where slug = 'tofu-mediterraneo'), 'GF'),
    ((select id from menu_items where slug = 'a-bella-figliola'), 'V'),
    ((select id from menu_items where slug = 'a-bella-figliola'), 'GF'),
    ((select id from menu_items where slug = 'a-bella-figliola'), 'VE'),
    ((select id from menu_items where slug = 'pizza-e-fantasia'), 'V'),
    ((select id from menu_items where slug = 'pizza-e-fantasia'), 'GF'),
    ((select id from menu_items where slug = 'pizza-e-fantasia'), 'VE'),
    ((select id from menu_items where slug = 'pizza-cacio-e-pepe'), 'V'),
    ((select id from menu_items where slug = 'pizza-cacio-e-pepe'), 'GF'),
    ((select id from menu_items where slug = 'alicella-sagliuta'), 'V'),
    ((select id from menu_items where slug = 'alicella-sagliuta'), 'GF'),
    ((select id from menu_items where slug = 'alicella-sagliuta'), 'VE'),
    ((select id from menu_items where slug = 'verdure-fresche'), 'V'),
    ((select id from menu_items where slug = 'verdure-fresche'), 'GF'),
    ((select id from menu_items where slug = 'verdure-fresche'), 'VE'),
    ((select id from menu_items where slug = 'pepperoni-doppio-formaggio'), 'GF'),
    ((select id from menu_items where slug = 'o-core-e-napule'), 'V'),
    ((select id from menu_items where slug = 'o-core-e-napule'), 'GF'),
    ((select id from menu_items where slug = 'o-core-e-napule'), 'VE'),
    ((select id from menu_items where slug = 'pizza-do-putecaro'), 'GF'),
    ((select id from menu_items where slug = 'pizza-bufala'), 'V'),
    ((select id from menu_items where slug = 'pizza-bufala'), 'GF'),
    ((select id from menu_items where slug = 'pizza-bufala'), 'VE'),
    ((select id from menu_items where slug = 'lazzarella'), 'GF'),
    ((select id from menu_items where slug = 'pollo-funghi-dolce'), 'GF'),
    ((select id from menu_items where slug = 'parmigiana-di-melanzane'), 'V'),
    ((select id from menu_items where slug = 'parmigiana-di-melanzane'), 'GF'),
    ((select id from menu_items where slug = 'parmigiana-di-melanzane'), 'VE'),
    ((select id from menu_items where slug = 'pollo-al-forno'), 'GF'),
    ((select id from menu_items where slug = 'triple-chocolate-brownie'), 'V'),
    ((select id from menu_items where slug = 'triple-chocolate-brownie'), 'GF'),
    ((select id from menu_items where slug = 'triple-chocolate-brownie'), 'VE'),
    ((select id from menu_items where slug = 'mixed-sides'), 'V'),
    ((select id from menu_items where slug = 'mixed-sides'), 'GF'),
    ((select id from menu_items where slug = 'mixed-sides'), 'VE'),
    ((select id from menu_items where slug = 'rocket-side'), 'V'),
    ((select id from menu_items where slug = 'rocket-side'), 'GF'),
    ((select id from menu_items where slug = 'rocket-side'), 'VE');

insert into menu_customizers (
    category_id,
    slug,
    name,
    base_price_pence,
    extra_topping_price_pence,
    active,
    display_order
)
values (
    (select id from menu_categories where slug = 'sourdough-pizza-calzone'),
    'create-your-own',
    'CREATE YOUR OWN',
    700,
    125,
    true,
    16
);

insert into pizza_toppings (customizer_id, name, available, display_order)
values
    ((select id from menu_customizers where slug = 'create-your-own'), 'Anchovies', true, 1),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Artichokes', true, 2),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Asparagus', true, 3),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Capers', true, 4),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Caramelised Onions', true, 5),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Pineapple', true, 6),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Courgettes', true, 7),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Fior di latte cheese', true, 8),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Fresh Chilli', true, 9),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Gluten Free Base', true, 10),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Goat cheese', true, 11),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Gorgonzola cheese', true, 12),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Mixed olives', true, 13),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Mushrooms', true, 14),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Nduja', true, 15),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Onions', true, 16),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Parma ham', true, 17),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Rainbow cherry tomatoes', true, 18),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Red onion marmalade', true, 19),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Ricotta cheese', true, 20),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Roasted ham', true, 21),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Spicy salami', true, 22),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Tomato sauce', true, 23),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Vegan cheese', true, 24),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Isle of Wight Roasted Tomato Sauce', true, 25),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Sweet Corn', true, 26),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Peppers', true, 27),
    ((select id from menu_customizers where slug = 'create-your-own'), 'Spicy jalapeños', true, 28);
