package com.basilico.backend.notification.entity;

public enum NotificationType {
	ORDER_RECEIVED,
	ORDER_ACCEPTED,
	ORDER_READY,
	ORDER_CANCELLED,
	ORDER_REFUNDED,
	BOOKING_REQUEST_RECEIVED,
	BOOKING_CONFIRMED,
	BOOKING_DECLINED,
	BOOKING_CANCELLED,
	RESTAURANT_NEW_ORDER,
	RESTAURANT_NEW_BOOKING,
	MANUAL_MESSAGE
}
